## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
zer_vec = np.zeros(10)
zer_vec

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [5]:
one_vec = np.ones(10)
one_vec

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [6]:
vec_25 = np.array([2.5] * 10)
vec_25

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
zer_vec = np.zeros(10)
zer_vec[4] = 1
zer_vec

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [8]:
rand_vec = np.random.random(10)
print(rand_vec)
print(rand_vec[::-1])

[ 0.06208174  0.08719633  0.55880525  0.6363182   0.58831063  0.22161128
  0.8639874   0.35406476  0.27336257  0.29926414]
[ 0.29926414  0.27336257  0.35406476  0.8639874   0.22161128  0.58831063
  0.6363182   0.55880525  0.08719633  0.06208174]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [9]:
new_matrix = np.arange(9).reshape(3,3)
new_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [12]:
arr = np.array([1,2,0,0,4,0])
print(np.where(arr==0))

(array([2, 3, 5], dtype=int64),)


Создать 3x3 единичную матрицу

In [14]:
matrix_one = np.ones(shape=(3,3))
matrix_one

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [15]:
arr333 = np.random.random((3,3,3))
arr333

array([[[ 0.86857937,  0.42542069,  0.06191191],
        [ 0.9502978 ,  0.33585326,  0.36356461],
        [ 0.63717998,  0.11320365,  0.29585216]],

       [[ 0.21805758,  0.34010058,  0.71030104],
        [ 0.99938549,  0.36635372,  0.96130681],
        [ 0.65369319,  0.10165072,  0.19921996]],

       [[ 0.94667668,  0.38506563,  0.08722061],
        [ 0.57300803,  0.14661415,  0.92983699],
        [ 0.67349907,  0.09583699,  0.44874118]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [16]:
vec = np.random.random(30)
print(vec)
print("Mean of vec = {}".format(vec.mean()))

[ 0.0993418   0.12443405  0.91885932  0.21631348  0.9948342   0.86373493
  0.05904891  0.6228534   0.42512888  0.27763419  0.22383388  0.30796513
  0.95271459  0.49269703  0.90832154  0.39145116  0.57646703  0.28607636
  0.26879956  0.48885015  0.69417666  0.58555661  0.21932191  0.94015561
  0.69458144  0.91964633  0.39417989  0.67015153  0.85829852  0.21478453]
Mean of vec = 0.523007088260803


Перемножить матрицы 5x3 и 3x2

In [17]:
a = np.random.random((5,3))
b = np.random.random((3,2))
c = np.matmul(a,b)
c

array([[ 0.92412468,  1.66298874],
       [ 0.29251229,  0.74867984],
       [ 0.31674604,  0.50420306],
       [ 0.76851058,  1.26107401],
       [ 0.38966148,  0.6515241 ]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [23]:
vec = np.random.uniform(0,1,10)
vec

array([ 0.17211416,  0.93070268,  0.25437652,  0.44577012,  0.39052795,
        0.42722869,  0.84024893,  0.19326618,  0.62297578,  0.76587056])

Заменить максимальный элемент на ноль

In [25]:
max_elem = vec.max()
print(vec)
print("**** Заменим максимальный элемент {}, c индексом {} на 0 ****".format(max_elem,np.where(vec==max_elem)[0]))
vec[vec == max_elem] = 0
print(vec)

[ 0.17211416  0.          0.25437652  0.44577012  0.39052795  0.42722869
  0.84024893  0.19326618  0.62297578  0.76587056]
**** Заменим максимальный элемент 0.8402489265463418, c индексом [6] на 0 ****
[ 0.17211416  0.          0.25437652  0.44577012  0.39052795  0.42722869
  0.          0.19326618  0.62297578  0.76587056]


Преобразовать массив из float в int

In [26]:
arr = np.random.uniform(1,100,5)
print(arr)
print(type(arr[0]))
arr = arr.astype(int)
print(arr)
print(type(arr[0]))

[ 48.71304037  25.16208151  58.55898048  20.76508751  82.57213316]
<class 'numpy.float64'>
[48 25 58 20 82]
<class 'numpy.int32'>


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [33]:
matrix = np.random.random((10,2))
#расстояние между двумя точками sqrt((x2-x1)^2 + (y2-y1)^2)
x = matrix[:,0]
y = matrix[:,1]
print(x)
print(y)
for i in range(0,10):
    for j in range(0,10):
        if (i < j):
            print("Расстояние от {} до {} = {}".format(i+1,j+1,np.sqrt((x[j]-x[i])**2 + (y[j]-y[i])**2)))

[ 0.22230965  0.76999829  0.04009834  0.76723615  0.50720368  0.41624964
  0.44266909  0.07676948  0.06056791  0.91850342]
[ 0.31178434  0.99534364  0.39068956  0.0509733   0.30094555  0.06742712
  0.29849379  0.11098385  0.06385878  0.19098508]
Расстояние от 1 до 2 = 0.8759087623002985
Расстояние от 1 до 3 = 0.19856232166691182
Расстояние от 1 до 4 = 0.6041252291564188
Расстояние от 1 до 5 = 0.2851001388464638
Расстояние от 1 до 6 = 0.3119666126890069
Расстояние от 1 до 7 = 0.2207598765336788
Расстояние от 1 до 8 = 0.24799753822277934
Расстояние от 1 до 9 = 0.29601938340990863
Расстояние от 1 до 10 = 0.7065962212717026
Расстояние от 2 до 3 = 0.9478188037095665
Расстояние от 2 до 4 = 0.9443743857697007
Расстояние от 2 до 5 = 0.7424619247776352
Расстояние от 2 до 6 = 0.9930595027090272
Расстояние от 2 до 7 = 0.7698987707083947
Расстояние от 2 до 8 = 1.1236807472404733
Расстояние от 2 до 9 = 1.1708780941963923
Расстояние от 2 до 10 = 0.8179526063988889
Расстояние от 3 до 4 = 0.8025811723

Случайно расположить p элементов в 2D массив

In [71]:
# a = np.arange(5)
# print(np.put(a, [0, 2], [-44, -55]))
# print(a)

# Указываем параметр n и p
n , p = 5 , 3
matrix = np.zeros((n,n))
p_elems= np.random.random(p)
print("Расположим следующие {} элемента-{}".format(p,p_elems))
for val in p_elems:
    np.put(matrix, np.random.choice(range(n*n), 1,replace=False), val)
matrix

Расположим следующие 3 элемента-[ 0.40102414  0.59601432  0.06434045]


array([[ 0.        ,  0.        ,  0.        ,  0.59601432,  0.        ],
       [ 0.        ,  0.06434045,  0.        ,  0.        ,  0.        ],
       [ 0.40102414,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [72]:
vec = np.array([1,2,3,4,5])
new_vec = np.zeros(20)
for i in range(0,5):
    new_vec[(i)*4] = vec[i]
new_vec

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.,  0.,  0.,  0.])

Найти наиболее частое значение в массиве

In [76]:
unq, pos = np.unique(new_vec,return_inverse=True)
cnt = np.bincount(pos)
max_elem = cnt.argmax()
print("Наиболее частое значение - {}".format(max_elem))

Наиболее частое значение - 0


Найти n наибольших значений в массиве

In [77]:
rd_arr = np.random.random(10)
n = 5 # Кол-во наибольших элементов в массиве
print(rd_arr)
sort_rd_arr = np.sort(rd_arr)
print(sort_rd_arr[n:])

[ 0.174162    0.54827807  0.55751304  0.46076462  0.69937859  0.07039583
  0.86465361  0.86691195  0.37001734  0.04308423]
[ 0.54827807  0.55751304  0.69937859  0.86465361  0.86691195]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [82]:
import pandas as pd
food = pd.read_csv("Z:\IT Validation Framework\Python validation\en.openfoodfacts.org.products.tsv", sep='\t', low_memory=False)

Посмотреть первые 5 записей

In [83]:
food.head(5)

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [84]:
len(food)

356027

Сколько столбцов в наборе данных?

In [85]:
len(food.columns)

163

Напечатайте все названия столбцов

In [86]:
food_columns_list = list(food.columns.values)
print(food_columns_list)

['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands', 'brands_tags', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'no_nutriments', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n', 'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags', 'ingredients_that_may_be_from_palm_oil_n', 'ingredients_that_may_be_from_palm_oil', 'ingredients_that_may_be_from_palm_oil_tags', 'nutrition_grade_uk', 'nutrition_grade_fr', 'pnns_groups_1', 

Какое название у 105 столбца?

In [87]:
food_columns_list[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [88]:
type(food_columns_list[105])

str

Как проиндексирован набор данных?

In [89]:
print(food.index)
print(food.index.values)
print("Индексы - последовательность целых чисел от 0 до 356027")

RangeIndex(start=0, stop=356027, step=1)
[     0      1      2 ..., 356024 356025 356026]
Индексы - последовательность целых чисел от 0 до 356027


Каково значение имени продукта в 19-м наблюдении?

In [90]:
food['product_name'][19]

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [92]:
chipo = pd.read_csv("Z:\IT Validation Framework\Python validation\chipotle.tsv", sep='\t', low_memory=False)
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

Как много продуктов стоят более чем $10.00?

In [103]:
chipo['item_price'].dtypes
#тип строка, преобразуем в число
chipo['price'] = chipo['item_price'].str[1:].astype(float)
#Так как цена указана за кол-во (quantity), то посчитаем цену для 1 предмета 
chipo['price_for_item'] = chipo['price'] / chipo['quantity'] 
len(chipo[chipo['price_for_item'] > 10.00])

1034

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [101]:
# Так как у одного предмета (идентичные названия) могут быть разные ингридиенты, выводим уникальные с кол-вом повторений
chipo.groupby(['item_name', 'price_for_item']).size().reset_index(name='freq')

item_name  price_for_item  freq
0        6 Pack Soft Drink            6.49    54
1            Barbacoa Bowl            8.69     3
2            Barbacoa Bowl            8.99     8
3            Barbacoa Bowl            9.25    28
4            Barbacoa Bowl           11.48     6
5            Barbacoa Bowl           11.49     1
6            Barbacoa Bowl           11.75    20
7         Barbacoa Burrito            8.69     2
8         Barbacoa Burrito            8.99    19
9         Barbacoa Burrito            9.25    46
10        Barbacoa Burrito           11.08     1
11        Barbacoa Burrito           11.48     1
12        Barbacoa Burrito           11.75    22
13   Barbacoa Crispy Tacos            8.99     2
14   Barbacoa Crispy Tacos            9.25     5
15   Barbacoa Crispy Tacos           11.48     1
16   Barbacoa Crispy Tacos           11.75     3
17     Barbacoa Salad Bowl            9.39     5
18     Barbacoa Salad Bowl           11.89     5
19     Barbacoa Soft Tacos            8.99     2
20     Barbacoa Soft Tacos            9.25    15
21     Barbacoa Soft Tacos           11.48     1
22     Barbacoa Soft Tacos           11.75     7
23           Bottled Water            1.09    27
24           Bottled Water            1.50   135
25                    Bowl            7.40     1
26                    Bowl            7.40     1
27                 Burrito            7.40     6
28             Canned Soda            1.09   104
29       Canned Soft Drink            1.25   301
..                     ...             ...   ...
109          Steak Burrito           11.08     5
110          Steak Burrito           11.48    21
111          Steak Burrito           11.75   101
112     Steak Crispy Tacos            8.69     1
113     Steak Crispy Tacos            8.99     9
114     Steak Crispy Tacos            9.25    14
115     Steak Crispy Tacos           11.75    11
116            Steak Salad            8.69     1
117            Steak Salad            8.99     3
118       Steak Salad Bowl            9.39    10
119       Steak Salad Bowl           11.89    19
120       Steak Soft Tacos            8.99    14
121       Steak Soft Tacos            9.25    32
122       Steak Soft Tacos           11.48     3
123       Steak Soft Tacos           11.75     6
124            Veggie Bowl            8.49    16
125            Veggie Bowl            8.75    24
126            Veggie Bowl           10.98     4
127            Veggie Bowl           11.25    41
128         Veggie Burrito            8.49    40
129         Veggie Burrito            8.75    18
130         Veggie Burrito           10.98     4
131         Veggie Burrito           11.25    33
132    Veggie Crispy Tacos            8.49     1
133           Veggie Salad            8.49     6
134      Veggie Salad Bowl            8.75     8
135      Veggie Salad Bowl           11.25    10
136      Veggie Soft Tacos            8.49     3
137      Veggie Soft Tacos            8.75     2
138      Veggie Soft Tacos           11.25     2

[139 rows x 3 columns]

Отсортировать по имени предмета

In [102]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  price  \
3389                                        [Diet Coke]    $12.98   12.98   
341                                         [Diet Coke]     $6.49    6.49   
1849                                             [Coke]     $6.49    6.49   
1860                                        [Diet Coke]     $6.49    6.49   
2713                                             [Coke]     $6.49    6.49   
3422                                             [Coke]     $6.49    6.49   
553                                         [Diet Coke]     $6.49    6.49   
1916                                        [Diet Coke]     $6.49    6.49   
1922                                             [Coke]     $6.49    6.49   
1937                                        [Diet Coke]     $6.49    6.49   
3836                                             [Coke]     $6.49    6.49   
298                                            [Sprite]     $6.49    6.49   
1976                                        [Diet Coke]     $6.49    6.49   
1167         

Сколько было заказано самого дорогого предмета?

In [106]:
print("Сумма самого дорого предмета - {}".format(chipo['price_for_item'].max()))
print("Общее кол-во самых дорогих предметов - {}".format(chipo[chipo['price_for_item']==chipo['price_for_item'].max()]['quantity'].sum()))

Сумма самого дорого предмета - 11.89
Общее кол-во самых дорогих предметов - 30


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [109]:
# Так как 1 запись - 1 заказ прдемета, просто посчитаем кол-во записей в таблице
len(chipo[chipo['item_name']=='Veggie Salad Bowl'])

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [110]:
len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)])

20